sudo: required
services:
  - docker
language: csharp
solution: Kiotlog.sln
mono: none
dotnet: 2.1.105
env:
  global:
    secure: UIht8NFnqh92z6NlpyflRk/7Wgz+q6YdkcA7YfuxFzr+RQkMbv3U7NK191hrm2vOkAmhX3zHtnds+DviDyg3/vF9PQa5McaXYHZuhNTCoPlh4RU34efmzK8uMOto2F2voZK1saIvLzFksBavc/+tUjsvFiQoF5MhnwxCQBYrps5gRf7GRJBYoeTs2vMlnbVqre348lS7tFvOhlyu6bp+KKwjqXGG6Z3nOphMQ/yj2YEfDPTAwMF5IeX6+iZFMIVs/NuuN9RP0FDoU/gFqCTISr+NQxMR8dEuiahWH5vEY/Fv7yKNYAgKU/52HKz5mhEU93xDVNC/LYgs7A3sVUiz8amzzOscxn3hsLMhf62EUKO1I4wLAKxRUiGXhc1+cawOAv1OL4jxJyF/rmKue+KcAq5EQedXOhHeBzTJ2P2abW8YF6wTHayrgw22AUTdwFE2q9DZ4Yq5kyxj1Ek7sSjtqAEeZzA/s653+bVxafw0vO8z6FoTqtgZduJWJWrrJGlDxLRQ+VGeithSOweCPSj8sRpPY3Pa2UxaYBTl9WEMhiJLqoQOZorEenVQS7ZTMLkNUcYQ1EIx9D+WWjiaI1LeS+G2/ppE2bLXw4SIzClpKSk7Szqla7COmoYLWmMeyCphyXBdecY3AiPoZwjXBNvMJgODvTSkeFnN3Fx6NA9zVs4=
script:
  - dotnet build
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t kiotlog/decoder -f Decoder/Dockerfile .
  - docker build -t kiotlog/httpreceiver -f HttpReceiver/Dockerfile .
  - docker build -t kiotlog/klsnreceiver -f KlsnReceiver/Dockerfile .
  - docker push kiotlog/decoder:latest
  - docker push kiotlog/httpreceiver:latest
  - docker push kiotlog/klsnreceiver:latest
