version: "3"

services:
  Decoder:
    image: kiotlog/decoder:arm32v7
    build:
      context: .
      dockerfile: Decoder/Dockerfile.arm32

  HttpReceiver:
    image: kiotlog/httpreceiver:arm32v7
    build:
      context: .
      dockerfile: HttpReceiver/Dockerfile.arm32

  KlsnReceiver:
    image: kiotlog/klsnreceiver:arm32v7
    build:
      context: .
      dockerfile: KlsnReceiver/Dockerfile.arm32
